apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-maxtdbdc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-quarkus-maxtdbdc:7abf1878c9b2abcde7007e257f351e37462b6eb2@sha256:be4e6d5ba3427cc1126e89add11234c53f5c5a7dd3208ba9643c397a538ed580
          name: container-image
